// <auto-generated />
namespace WebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedDocumentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDocumentType));
        
        string IMigrationMetadata.Id
        {
            get { return "201707110947049_addedDocumentType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
