// <auto-generated />
namespace WebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApproverQuestion_IsAsked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApproverQuestion_IsAsked));
        
        string IMigrationMetadata.Id
        {
            get { return "201710230536216_ApproverQuestion_IsAsked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
