// <auto-generated />
namespace WebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PPRF_Enhancement_Dec2020_P1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PPRF_Enhancement_Dec2020_P1));
        
        string IMigrationMetadata.Id
        {
            get { return "202012170201181_PPRF_Enhancement_Dec2020_P1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
