// <auto-generated />
namespace WebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PPRF_Enhancement_Mar2021_Part2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PPRF_Enhancement_Mar2021_Part2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103170611171_PPRF_Enhancement_Mar2021_Part2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
